
name: Bug report
description: Report any issues you have found
title: "[Bug] "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Type what happened here.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Bug reproduction steps
      description: Steps to reproduce bug behavior.
      placeholder: Steps to reproduce the bug.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Garry's Mod version
      description: What version of GMod are you using when this bug happened?
      options:
        - Default (if you don't know/are running non-Steam, just pick this one)
        - Development Branch ("dev" option in Steam)
        - Prerelease Branch ("prerelease" option in Steam)
        - x86-64 Branch ("x86-64" option in Steam)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: gametype
    attributes:
      label: Game type
      description: What game type (not gamemode!) were you using?
      options:
        - Singleplayer
        - Multiplayer (if it happened with 2+ players, it's definitely this)
      default: 0
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context about the problem here. Not required, but helpful.
      placeholder: e.g. changed Beatrun settings, addon list
    validations:
      required: false